FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

RUN \
    apt-get update && \
    apt-get install -y --no-install-recommends \
        g++ cmake ninja-build ccache pkg-config git ca-certificates make

RUN \
    git clone --depth=1 https://github.com/OpenMathLib/OpenBLAS && \
    cd OpenBLAS && \
    make -j8 && \
    make install

WORKDIR /scripts
